export const tmpMap = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                   g    x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];
