export const map1 = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                   g    x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];

export const map2 = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                      xxxxxxxxx                         x",
    "x s                                      x                                 x",
    "x s                                      x                                 x",
    "x s                                      x   g                             x",
    "x s                                      x                                 x",
    "x s                                      x                                 x",
    "x s                                      xxxxxxxxx                         x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "x s                                                                        x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];
