export const map0 = ["xxxxx", "xs  x", "xs gx", "xxxxx"];

export const map1 = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                          g             x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "x s                                                        x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];

export const map2 = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                       xxxxxxxxx                         x",
    "x s                       x                                 x",
    "x s                       x                                 x",
    "x s                           g                             x",
    "x s                       x                                 x",
    "x s                       x                                 x",
    "x s                       xxxxxxxxx                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "x s                                                         x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];

export const map3 = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x s                                                                    x",
    "x s                    x                                               x",
    "x s                    x                                               x",
    "x s                    x                                               x",
    "x s                    x                 xxx   xxx                     x",
    "x s                                      x       x                     x",
    "x s                         x            x       x                     x",
    "x s                         x            x   g   x                     x",
    "x s                         x            x       x                     x",
    "x s                                      x       x                     x",
    "x s                    x                 xxx   xxx                     x",
    "x s                    x                                               x",
    "x s                    x                                               x",
    "x s                    x                                               x",
    "x s                                                                    x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];

export const map4 = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x s                                   x",
    "x s                                   x",
    "x s                                   x",
    "x s                                   x",
    "x s                                   x",
    "x s                                   x",
    "x s                                   x",
    "x s                                   x",
    "x s                                   x",
    "x s                                   x",
    "x s                                   x",
    "xxxxxxxxxxxxxxxxxxxxxxxxx             x",
    "x         xxxxxxxxxxxxxxx             x",
    "x    g    xxxxxxxxxxxxxxx             x",
    "x         xxxxxxxxxxxxxxx             x",
    "x         xxxxxxxxxxxxxxx             x",
    "x         xxxxxxxxxxxxxxx             x",
    "x         xxxxxxxxxxxxxxx             x",
    "x         xxxxxxxxxxxxxxx             x",
    "x                                     x",
    "x                                     x",
    "x                                     x",
    "x                                     x",
    "x                                     x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];

export const map5 = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x s                              xxxxxxx xxxxxx                                   xxxxxxxxxx",
    "x s                             xxxxxxxx xxxxxx                                   xxxxxxxxxx",
    "x s                            xxxxxxxxx xxxxxx                                   xxxxxxxxxx",
    "x s                           xxxxxxxxxx xxxxxx                                   xxxxxxxxxx",
    "x s                            xxxxxxxxx xxxxxx                                   xxxxxxxxxx",
    "x s                             xxxxxxxx xxxxxx                                   xxxxxxxxxx",
    "x s                              xxxxxxx xxxxxx                                   xxxxxxxxxx",
    "x s                               xxxxxx xxxxxx          xxxxxxxxxx               xxxxxxxxxx",
    "x s                                                      x      x                          x",
    "x s                                                      x      x                          x",
    "x s                                                      x      x                          x",
    "x s                                                      x              xxxxxxxxxx         x",
    "x s                                                      x                xxxxxxxx         x",
    "x s                               xxxxxx xxxxxx          xxxxxxxxxx         xxxxxx         x",
    "x s                              xxxxxxx xxxxxx                               xxxx         x",
    "x s                             xxxxxxxx xxxxxx                                 xx    g    x",
    "x s                            xxxxxxxxx xxxxxx                                  x         x",
    "x s                           xxxxxxxxxx xxxxxx                                            x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];

export const map6 = [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x s                                  xx                                                                   x",
    "x s                                  xx                                           xx                      x",
    "x s                                  xx                                                                   x",
    "x s                                  xx                                         xx                        x",
    "x s                                  xx                         /  xxxxxxxxxxxxxx                         x",
    "x s                                  xx                        /                                          x",
    "x s                                  xx                       /                                           x",
    "x s                                                          /         xxxxxxxxxx              x          x",
    "x s                                                         /                   x             x           x",
    "x s                                   x                     xx                  x            x            x",
    "x s                                  xx                     xx            g     x           x             x",
    "x s                                   x                     xx                  x            x            x",
    "x s                                                          xx                 x             x           x",
    "x s                                                           xx       xxxxxxxxxx              x          x",
    "x s                                  xx                        xx                                         x",
    "x s                                  xx                         xx                                        x",
    "x s                                  xx                          xxxxxxxxxxxxxxxx                         x",
    "x s                                  xx                                         xx                        x",
    "x s                                  xx                                                                   x",
    "x s                                  xx                                           xx                      x",
    "x s                                  xx                                                                   x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];

let currentMap = 0;

const maps = [map0, map1, map2, map3, map4, map5, map6];

export function getNextMap() {
    currentMap = (currentMap + 1) % maps.length;

    return map6;

    return maps[currentMap];
}
