const randomNamesList: string[] = [
    "Lord of the Greens",
    "King of the Fairway",
    "Mighty Mulligan",
    "Sir Bogey",
    "Golden Putter",
    "Lucky Birdie",
    "Grand Shank",
    "Royal Divot",
    "Fairway Fury",
    "Midnight Mulligan",
    "Thunder Putt",
    "Velvet Bogey",
    "Silver Wedge",
    "Crimson Caddy",
    "Noble Shank",
    "Gallant Golfer",
    "Rapid Rabbit",
    "Swift Swinger",
    "Dashing Divot",
    "Flying Fairway",
    "Brilliant Birdie",
    "Bold Bogey",
    "Mighty Wedge",
    "Duke of the Rough",
    "Prince of Putt",
    "Baron Bogey",
    "Sir Shanksalot",
    "Count of Caddy",
    "Lord Mulligan",
    "Captain Birdie",
    "Major Putter",
    "General Bogey",
    "Admiral Wedge",
    "The Great Puttowski",
    "Puttin' On Airs",
    "Fore and Glory",
    "Par for Glory",
    "Born to Bogey",
    "Running on Pars",
    "One More Putt",
    "Never on the Green",
    "Lost in the Rough",
    "Straight Down Fairway",
    "Caught in the Bunker",
    "Shank Redemption",
    "A Stroke of Genius",
    "A Touch of Class",
    "Labain Meier",
    "Fairway to Heaven",
    "Frida Kranstege",
];

export function getRandomName(): string {
    let randomIndex = Math.floor(Math.random() * 50);

    return randomNamesList[randomIndex];
}
